import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import KpiCard from '../components/ui/KpiCard'
import UploadZone from '../components/ui/UploadZone'
import Spinner from '../components/ui/Spinner'
import InfoBox from '../components/ui/InfoBox'
import { useToast } from '../components/ui/Toast'
import { ArrowUpRight, RefreshCw, Database, Layers, UploadCloud } from 'lucide-react'

function percent(value) {
  if (value == null || Number.isNaN(Number(value))) return '—'
  return `${Math.round(value * 100)}%`
}

function safeNumber(value) {
  return typeof value === 'number' ? value : parseFloat(value) || 0
}

function StatsRow({ label, value }) {
  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 10, alignItems: 'center', padding: '10px 0', borderBottom: '1px solid rgba(15, 23, 42, 0.08)' }}>
      <span style={{ color: 'var(--tm)', fontSize: 12 }}>{label}</span>
      <span style={{ color: 'var(--tp)', fontSize: 13, fontWeight: 600 }}>{value}</span>
    </div>
  )
}

export default function LearningPage() {
  const [actualFile, setActualFile] = useState(null)
  const toast = useToast()
  const queryClient = useQueryClient()

  const summaryQuery = useQuery({
    queryKey: ['datasetSummary'],
    queryFn: () => api.getDatasetSummary().then(r => r.data),
  })

  const forecastQuery = useQuery({
    queryKey: ['autoForecast'],
    queryFn: () => api.getAutoForecast().then(r => r.data),
  })

  const graphStatsQuery = useQuery({
    queryKey: ['graphStats'],
    queryFn: () => api.getGraphStats().then(r => r.data),
    refetchInterval: 30_000,
  })

  const tpkeStatusQuery = useQuery({
    queryKey: ['tpkeStatus'],
    queryFn: () => api.getTpkeStatus().then(r => r.data),
    refetchInterval: 30_000,
    retry: false,
  })

  const tpkeSummaryQuery = useQuery({
    queryKey: ['tpkeSummary'],
    queryFn: () => api.getTpkeSummary().then(r => r.data),
    refetchInterval: 30_000,
    retry: false,
  })

  const tpkeEdgesQuery = useQuery({
    queryKey: ['tpkeEdges'],
    queryFn: () => api.getTpkeEdges().then(r => r.data),
    refetchInterval: 30_000,
    retry: false,
  })

  const uploadActual = useMutation({
    mutationFn: (file) => api.uploadActual(file).then(r => r.data),
    onSuccess: () => {
      toast.success('Actual dataset uploaded and validated by backend.')
      setActualFile(null)
      queryClient.invalidateQueries(['tpkeStatus', 'tpkeSummary', 'tpkeEdges', 'graphStats', 'autoForecast'])
    },
    onError: (err) => toast.error(err.message || 'Actual upload failed'),
  })

  const evolveTpke = useMutation({
    mutationFn: () => api.evolveTpke({ triggered_by: 'ui' }).then(r => r.data),
    onSuccess: (data) => {
      toast.success('TPKE learning cycle executed successfully.')
      queryClient.invalidateQueries(['tpkeStatus', 'tpkeSummary', 'tpkeEdges', 'graphStats'])
    },
    onError: (err) => toast.error(err.message || 'TPKE cycle failed'),
  })

  const decayTpke = useMutation({
    mutationFn: () => api.decayTpke({}).then(r => r.data),
    onSuccess: () => {
      toast.success('TPKE decay pass completed successfully.')
      queryClient.invalidateQueries(['tpkeStatus', 'tpkeSummary', 'tpkeEdges', 'graphStats'])
    },
    onError: (err) => toast.error(err.message || 'TPKE decay failed'),
  })

  const isLoading = summaryQuery.isLoading || forecastQuery.isLoading
  if (isLoading) {
    return <Spinner large text="Loading learning cycle data from backend APIs..." />
  }

  if (summaryQuery.isError) {
    return <InfoBox type="error">{summaryQuery.error?.message || 'Unable to load learning cycle data'}</InfoBox>
  }

  const summary = summaryQuery.data || {}
  const forecast = forecastQuery.data || {}
  const graphStats = graphStatsQuery.data || {}
  const tpkeStatus = tpkeStatusQuery.data || {}
  const tpkeSummary = tpkeSummaryQuery.data || {}
  const tpkeEdges = tpkeEdgesQuery.data || {}

  const steps = [
    { label: 'Forecast generated by backend', icon: ArrowUpRight },
    { label: 'Actuals uploaded and compared', icon: UploadCloud },
    { label: 'TPKE detects temporal patterns', icon: Layers },
    { label: 'Knowledge graph evolves with new links', icon: Database },
  ]

  return (
    <div className="page active">
      <div className="page-head">
        <div>
          <div className="page-title">Learning Cycle</div>
          <div className="page-sub">Close the loop with actual performance, TPKE evolution and knowledge graph learning.</div>
        </div>
        <span className="badge bdg-blue">Data Source: Forecast + Actual Upload + TPKE</span>
      </div>

      <div className="g3">
        <KpiCard
          label="Next Forecast Period"
          value={forecast.forecast_period || 'n/a'}
          unit=""
          foot="Forecast APIs"
          color="var(--blue)"
        />
        <KpiCard
          label="TPKE Edge Count"
          value={tpkeEdges.count ?? 0}
          foot="Knowledge Graph"
          color="var(--inv)"
        />
        <KpiCard
          label="Graph Relationships"
          value={graphStats.total_relationships ?? 0}
          foot="Neo4j Knowledge Graph"
          color="var(--sup)"
        />
      </div>

      <div className="g2">
        <div className="card">
          <div className="card-head">
            <span className="card-title">Upload Actuals</span>
          </div>
          <div className="card-body" style={{ display: 'grid', gap: '16px' }}>
            <p style={{ color: 'var(--ts)', fontSize: 13, lineHeight: 1.6 }}>
              Upload actual demand and shipment results to validate the forecast and trigger TPKE learning from real outcomes.
            </p>
            <UploadZone
              accept=".csv"
              hint="Drop actuals CSV or click to upload"
              onFile={setActualFile}
              hasFile={!!actualFile}
              fileName={actualFile?.name}
              onClear={() => setActualFile(null)}
              disabled={uploadActual.isLoading}
            />
            <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', alignItems: 'center' }}>
              <button
                className="btn btn-primary"
                disabled={!actualFile || uploadActual.isLoading}
                onClick={() => uploadActual.mutate(actualFile)}
              >
                {uploadActual.isLoading ? 'Uploading...' : 'Upload Actuals'}
              </button>
              <span style={{ color: 'var(--tm)', fontSize: 12 }}>
                Last refresh: {forecast.generated_at ? new Date(forecast.generated_at).toLocaleString() : 'N/A'}
              </span>
            </div>
            {uploadActual.isError && (
              <InfoBox type="error">{uploadActual.error?.message || 'Actual upload failed'}</InfoBox>
            )}
          </div>
        </div>

        <div className="card">
          <div className="card-head">
            <span className="card-title">TPKE Knowledge Evolution</span>
          </div>
          <div className="card-body">
            <div className="g2" style={{ marginBottom: '12px' }}>
              <div style={{ display: 'grid', gap: '6px' }}>
                <span className="section-lbl">Engine Status</span>
                <span style={{ color: 'var(--tp)', fontWeight: 600 }}>{tpkeStatus.status || 'Unknown'}</span>
              </div>
              <div style={{ display: 'grid', gap: '6px' }}>
                <span className="section-lbl">Config Snapshot</span>
                <span style={{ color: 'var(--tm)', fontSize: 12 }}>
                  Window {tpkeStatus.window_size_days ?? '–'} days · Frequency threshold {tpkeStatus.frequency_threshold ?? '–'} · Confidence {percent(tpkeStatus.confidence_threshold ?? tpkeStatus.threshold ?? 0)}
                </span>
              </div>
            </div>
            <div style={{ display: 'grid', gap: '10px' }}>
              {Object.entries(tpkeSummary).length > 0 ? (
                Object.entries(tpkeSummary).map(([key, value]) => (
                  <StatsRow key={key} label={key.replace(/_/g, ' ')} value={value} />
                ))
              ) : (
                <div style={{ color: 'var(--tm)', fontSize: 12 }}>TPKE summary metrics are not available yet.</div>
              )}
            </div>
          </div>
          <div className="card-foot" style={{ display: 'flex', justifyContent: 'space-between', gap: '10px', flexWrap: 'wrap' }}>
            <button className="btn btn-secondary btn-sm" onClick={() => evolveTpke.mutate()} disabled={evolveTpke.isLoading}>
              {evolveTpke.isLoading ? 'Running TPKE...' : 'Run TPKE Evolution'}
            </button>
            <button className="btn btn-secondary btn-sm" onClick={() => decayTpke.mutate()} disabled={decayTpke.isLoading}>
              {decayTpke.isLoading ? 'Decaying...' : 'Decay TPKE Edges'}
            </button>
          </div>
        </div>
      </div>

      <div className="card">
        <div className="card-head">
          <div>
            <span className="card-title">Learning Cycle Narrative</span>
            <div className="card-meta">Track how forecast output and actual records feed into TPKE and update the graph.</div>
          </div>
        </div>
        <div className="card-body" style={{ display: 'grid', gap: '16px' }}>
          <div style={{ display: 'grid', gap: '10px', gridTemplateColumns: '1fr 1fr', alignItems: 'flex-start' }}>
            {steps.map((step, idx) => (
              <div key={idx} style={{ display: 'flex', gap: '10px', padding: '12px 14px', background: 'var(--s2)', borderRadius: '12px', border: '1px solid var(--b)' }}>
                <div style={{ width: 32, height: 32, borderRadius: 10, background: 'rgba(9,132,227,0.12)', display: 'grid', placeItems: 'center', color: 'var(--blue)' }}>
                  <step.icon size={18} />
                </div>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--tp)' }}>{step.label}</div>
                  <div style={{ color: 'var(--tm)', fontSize: 12, marginTop: 4 }}>
                    Backend-managed stage. Predictions are generated, actuals are aligned, and graph heuristic learning is executed server-side.
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div style={{ color: 'var(--tm)', fontSize: 12, lineHeight: 1.7 }}>
            The Learning Cycle page links forecast outputs to actual performance and the TPKE engine. This stage does not compute predictions in the browser — it only visualizes the backend learning flow and exposes status from FastAPI, Neo4j and TPKE services.
          </div>
        </div>
      </div>
    </div>
  )
}
