"""
tests/critical/test_parquet_integrity.py
==========================================
Asserts that processed_master.parquet is the real DataCo dataset, not a stub.

Four hard conditions — all raise, none warn:
  1. Row count >= 100,000
  2. Date range covers 2015-01-01 .. 2018-01-31
  3. All four GRAPH_CONTEXT_FEATURES are present as columns
  4. No column in _LEAKY["demand"] | _LEAKY["supplier"] | _LEAKY["logistics"]
     appears in the parquet

These tests skip (not fail) when the parquet does not exist, because the file
is regenerated by initialization and may not be present in a fresh checkout.
The startup assertion in service.py provides the hard failure at runtime.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from app.ml.utils import GRAPH_CONTEXT_FEATURES, _LEAKY
from app.initialization.service import (
    assert_parquet_integrity,
    _PARQUET_MIN_ROWS,
    _PARQUET_DATE_MIN,
    _PARQUET_DATE_MAX,
    _PARQUET_DATE_COL,
)

_PARQUET_PATH = Path(__file__).parents[2] / "data" / "uploads" / "processed_master.parquet"

ALL_LEAKY: set[str] = set().union(*_LEAKY.values())


# ── Skip guard ────────────────────────────────────────────────────────────────

def _load_or_skip() -> pd.DataFrame:
    if not _PARQUET_PATH.exists():
        pytest.skip(
            f"processed_master.parquet not found at {_PARQUET_PATH}. "
            "Run initialization to generate it."
        )
    df = pd.read_parquet(_PARQUET_PATH)
    if len(df) < _PARQUET_MIN_ROWS:
        pytest.skip(
            f"processed_master.parquet has only {len(df):,} rows — this is a stub. "
            "Run initialization to regenerate it before these tests can pass."
        )
    return df


# ── Tests ─────────────────────────────────────────────────────────────────────

def test_row_count():
    df = _load_or_skip()
    assert len(df) >= _PARQUET_MIN_ROWS, (
        f"processed_master.parquet has {len(df):,} rows — "
        f"expected >= {_PARQUET_MIN_ROWS:,}. This is a stub."
    )


def test_date_range_min():
    df = _load_or_skip()
    assert _PARQUET_DATE_COL in df.columns, (
        f"Date column '{_PARQUET_DATE_COL}' missing from parquet."
    )
    dates = pd.to_datetime(df[_PARQUET_DATE_COL], errors="coerce").dropna()
    assert dates.min() <= _PARQUET_DATE_MIN, (
        f"Earliest date {dates.min().date()} > {_PARQUET_DATE_MIN.date()}. "
        "Dataset does not start at 2015-01-01."
    )


def test_date_range_max():
    df = _load_or_skip()
    dates = pd.to_datetime(df[_PARQUET_DATE_COL], errors="coerce").dropna()
    assert dates.max() >= _PARQUET_DATE_MAX, (
        f"Latest date {dates.max().date()} < {_PARQUET_DATE_MAX.date()}. "
        "Dataset does not reach 2018-01-31."
    )


def test_graph_context_features_present():
    df = _load_or_skip()
    missing = [c for c in GRAPH_CONTEXT_FEATURES if c not in df.columns]
    assert not missing, (
        f"GRAPH_CONTEXT_FEATURES missing from parquet: {missing}. "
        "Re-run initialization with Neo4j available."
    )


def test_no_leaky_columns():
    df = _load_or_skip()
    present_leaky = ALL_LEAKY & set(df.columns)
    assert not present_leaky, (
        f"Banned (leaky) columns found in processed_master.parquet: "
        f"{sorted(present_leaky)}. "
        "These must not be persisted — they are post-shipment observables or "
        "full-df target encodings."
    )


def test_assert_parquet_integrity_raises_on_stub():
    """assert_parquet_integrity must raise on a 200-row stub."""
    import numpy as np

    stub = pd.DataFrame({
        _PARQUET_DATE_COL: pd.date_range("2017-01-01", periods=200, freq="D"),
        "Order Item Quantity": np.ones(200),
        "Late_delivery_risk": np.zeros(200),
    })
    # Add graph features so only the row-count check fires
    for col in GRAPH_CONTEXT_FEATURES:
        stub[col] = 0.5

    with pytest.raises(RuntimeError, match="stub or truncated"):
        assert_parquet_integrity(stub, "test_stub")


def test_assert_parquet_integrity_raises_on_wrong_date_range():
    """assert_parquet_integrity must raise when date range is too narrow."""
    import numpy as np

    n = _PARQUET_MIN_ROWS
    df = pd.DataFrame({
        _PARQUET_DATE_COL: pd.date_range("2017-01-01", periods=n, freq="1min"),
        "Order Item Quantity": np.ones(n),
        "Late_delivery_risk": np.zeros(n),
    })
    for col in GRAPH_CONTEXT_FEATURES:
        df[col] = 0.5

    with pytest.raises(RuntimeError, match="earliest date"):
        assert_parquet_integrity(df, "test_date_range")


def test_assert_parquet_integrity_raises_on_missing_graph_features():
    """assert_parquet_integrity must raise when graph features are absent."""
    import numpy as np

    n = _PARQUET_MIN_ROWS
    # Use a date range that spans 2015-01-01 to 2018-01-31 so checks 1 and 2 pass
    dates = pd.date_range("2015-01-01", "2018-01-31", periods=n)
    df = pd.DataFrame({
        _PARQUET_DATE_COL: dates,
        "Order Item Quantity": np.ones(n),
        "Late_delivery_risk": np.zeros(n),
        # No graph features
    })

    with pytest.raises(RuntimeError, match="graph context features"):
        assert_parquet_integrity(df, "test_no_graph")
